name: ${project.name}
version: ${project.version}
main: com.imjustdoom.bettermessages.BetterMessages
api-version: 1.13
authors: [ JustDoom ]
softdepend:
  - PlaceholderAPI
  - BetterReload

permissions:
  bettermessages.silent-join:
    default: false
    description: Allows user to join silently always
  bettermessages.silent-quit:
    default: false
    description: Allows user to quit silently always
  bettermessages.silent-world-change:
    default: false
    description: Allows user to change worlds silently always
  bettermessages.reload:
    default: op
    description: Allows access to /bettermessages reload
  bettermessages.help:
    default: op
    description: Allows access to /bettermessages help
  bettermessages.editmsg:
    default: op
    description: Allows access to /bettermessages editmsg
  bettermessages:
    default: op
    description: Allows access to /bettermessages (Base permission for all commands)

commands:
  bettermessages:
    aliases:
      - bm
    permission: bettermessages