#DO NOT TOUCH THIS SETTING
config-version: 11

disable-outdated-config-warning: false

messages:
  join:
    enabled: true

    # Set to -1 to disable
    count:
      - -1
    permission: none
    message: '&eWelcome &f&l{player} &eto the server!'

    # Options
    # server - everyone in the server
    # world - everyone in the world the player is currently in
    # world/{world} - specify a world to send the messages to
    audience: server
    activation:
      - join
  first-join:
    enabled: true
    count:
      - 1
    permission: none
    message: '&eWelcome &f&l{player} &eto the server for the first time!'
    audience: server
    activation:
      - join
  quit:
    enabled: true
    permission: none
    message: '&f&l{player} &equit :('
    audience: server
    activation:
      - quit
  entered-nether:
    enabled: true
    permission: none
    message: '&f&l{player} &eentered the nether, be careful!'
    audience: server
    activation:
      - world-change/world/world_nether













join:
  enabled: true
  # The permission people will need to see the message
  permission: none
  message-type:
    chat-message: true
    action-bar: false
    title-message: false
  message: '&eWelcome &f&l{player} &eto the server!'
  first-join:
    enabled: true
    # The permission people will need to see the message
    permission: none
    message-type:
      chat-message: true
      action-bar: false
      title-message: false
    message: '&eWelcome &f&l{player} &eto the server for the first time!'
    only-to-player: false

quit:
  enabled: true
  # The permission people will need to see the message
  permission: none
  message-type:
    chat-message: true
    action-bar: false
    title-message: false
  message: '&f&l{player} &eleft the server :('

world-change:
  1:
    enabled: true
    # The permission people will need to see the message
    permission: none
    message-type:
      chat-message: true
      action-bar: false
      title-message: false
    replace-underscore: true
    from: 'world'
    to: 'world_nether'
    message: '&f&l{player} &eleft the &c{from} &eand entered the &c{to}'
    only-to-player: false