#DO NOT TOUCH THIS SETTING
config-version: 11

disable-outdated-config-warning: false

join:
  enabled: true
  # The permission people will need to see the message
  permission: none
  message-type:
    chat-message: true
    action-bar: false
    title-message: false
  message: '&eWelcome &f&l{player} &eto the server!'
  first-join:
    enabled: true
    # The permission people will need to see the message
    permission: none
    message-type:
      chat-message: true
      action-bar: false
      title-message: false
    message: '&eWelcome &f&l{player} &eto the server for the first time!'
    only-to-player: false

quit:
  enabled: true
  # The permission people will need to see the message
  permission: none
  message-type:
    chat-message: true
    action-bar: false
    title-message: false
  message: '&f&l{player} &eleft the server :('

world-change:
  1:
    enabled: true
    # The permission people will need to see the message
    permission: none
    message-type:
      chat-message: true
      action-bar: false
      title-message: false
    replace-underscore: true
    from: 'world'
    to: 'world_nether'
    message: '&f&l{player} &eleft the &c{from} &eand entered the &c{to}'
    only-to-player: false